USE [master]
GO
/****** Object:  Database [IranMapDB]    Script Date: 08/04/1404 11:11:04 ******/
CREATE DATABASE [IranMapDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IranMapDB', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\IranMapDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IranMapDB_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\IranMapDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [IranMapDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IranMapDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IranMapDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IranMapDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IranMapDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IranMapDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IranMapDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [IranMapDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IranMapDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IranMapDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IranMapDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IranMapDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IranMapDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IranMapDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IranMapDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IranMapDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IranMapDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [IranMapDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IranMapDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IranMapDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IranMapDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IranMapDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IranMapDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [IranMapDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IranMapDB] SET RECOVERY FULL 
GO
ALTER DATABASE [IranMapDB] SET  MULTI_USER 
GO
ALTER DATABASE [IranMapDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IranMapDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IranMapDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IranMapDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IranMapDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IranMapDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'IranMapDB', N'ON'
GO
ALTER DATABASE [IranMapDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [IranMapDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [IranMapDB]
GO
/****** Object:  User [pouria]    Script Date: 08/04/1404 11:11:05 ******/
CREATE USER [pouria] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 08/04/1404 11:11:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Counties]    Script Date: 08/04/1404 11:11:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Counties](
	[CountyId] [int] IDENTITY(1,1) NOT NULL,
	[ProvinceCode] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Population] [int] NOT NULL,
	[Area] [float] NOT NULL,
 CONSTRAINT [PK_Counties] PRIMARY KEY CLUSTERED 
(
	[CountyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Provinces]    Script Date: 08/04/1404 11:11:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Provinces](
	[ProvinceCode] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Capital] [nvarchar](max) NOT NULL,
	[Population] [int] NOT NULL,
	[Area] [float] NOT NULL,
 CONSTRAINT [PK_Provinces] PRIMARY KEY CLUSTERED 
(
	[ProvinceCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProvinceStats]    Script Date: 08/04/1404 11:11:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProvinceStats](
	[ProvinceCode] [int] NOT NULL,
	[Population] [int] NULL,
	[UnemploymentRate] [float] NULL,
	[GDP] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProvinceCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Counties_ProvinceCode]    Script Date: 08/04/1404 11:11:05 ******/
CREATE NONCLUSTERED INDEX [IX_Counties_ProvinceCode] ON [dbo].[Counties]
(
	[ProvinceCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Counties]  WITH CHECK ADD  CONSTRAINT [FK_Counties_Provinces_ProvinceCode] FOREIGN KEY([ProvinceCode])
REFERENCES [dbo].[Provinces] ([ProvinceCode])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Counties] CHECK CONSTRAINT [FK_Counties_Provinces_ProvinceCode]
GO
USE [master]
GO
ALTER DATABASE [IranMapDB] SET  READ_WRITE 
GO
